version: '3'
services:
  mlmd-server:
    image: gcr.io/tfx-oss-public/ml_metadata_store_server:1.14.0
    container_name: mlmd-server
    ports:
      - "9090:8080"
    environment:
      - METADATA_STORE_SERVER_CONFIG_FILE=/tmp/shared/conn_config.pb
    volumes:
      - ./test/config/ml-metadata:/tmp/shared
  model-registry:
    build:
      context: .
      dockerfile: Dockerfile
    # command: ["proxy", "--mlmd-hostname", "mlmd-server", "--mlmd-port", "9090"]
    # command: ["proxy", "--mlmd-hostname", "mlmd-server", "--mlmd-port", "8080"]
    command: ["proxy", "--mlmd-hostname", "host.containers.internal", "--mlmd-port", "9090"]
    container_name: model-registry
    ports:
      - "8080:8080"
    depends_on:
      - mlmd-server
  # hello:
  #   image: crccheck/hello-world
  #   container_name: hello
  #   ports:
  #     - "8000:8000"
